name: Frontend CI

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: |
          cd src
          npm ci

      - name: Run linter
        run: |
          cd src
          npm run lint

      - name: Run tests
        run: |
          cd src
          npm test

      - name: Build
        run: |
          cd src
          npm run build 